[package]
name = "word2vec"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.15"
ndarray-rand = "0.14"
rand = "0.8"
itertools = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray-npy = "0.9.1"
